# Import theme
# Themes can be downloaded from https://github.com/alacritty/alacritty-theme
[general]
import = ["~/.config/alacritty/themes/solarized_dark.toml"]

[font]
size = 12

[font.glyph_offset]
x = -1
y = -1

# Download: https://github.com/romkatv/powerlevel10k#manual-font-installation
[font.normal]
family = "MesloLGS NF"
style = "Regular"

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
