import = ["~/.config/alacritty/solarized.toml"]

[font]
size = 12

[font.glyph_offset]
x = -1
y = -1

# Download: https://github.com/romkatv/powerlevel10k#manual-font-installation
[font.normal]
family = "MesloLGS NF"
style = "Regular"
